spring:
  jpa:
    database: POSTGRESQL
    open-in-view: true
    show-sql: true
    hibernate:
      # FIXME create update
      ddl-auto: create
    database-platform: org.hibernate.dialect.ProgressDialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.3.127:5432/auto-form
    username: postgres
    password: scyj123
    # 连接池设置。初始化大小，最小，最大
    druid:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://192.168.3.127:5432/auto-form
      username: postgres
      password: scyj123
      initialSize: 1
      minIdle: 3
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 30000
      filter:
        stat:
          log-slow-sql: true
          db-type: postgresql
          enabled: true
